name: Deploy Edge via AWS IoT

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: Edge_Vagrant_Secrets 

    steps:

      - name: Install mosquitto
        run: |
          sudo apt-get update
          sudo apt-get install -y mosquitto-clients

      - name: Create cert files
        run: |
          echo "${{ secrets.AWS_CERT }}" > cert.pem
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private.key
          echo "${{ secrets.AWS_CA }}" > root-CA.crt

      - name: Send MQTT trigger
        run: |
          mosquitto_pub \
            -h "${{ secrets.AWS_IOT_ENDPOINT }}" \
            -p 8883 \
            --cafile root-CA.crt \
            --cert cert.pem \
            --key private.key \
            -t deploy/vagrant-edge-device \
            -m update