Vagrant.configure("2") do |config|

  PREFIX  = "iot"
  NETWORK = "192.168.56."
  config.vm.boot_timeout = 300
  config.ssh.forward_agent = false
  BOX = "ubuntu/jammy64"
  
 # BOX_VERSION = "1.0"

  # 🔧 Config par défaut (adaptée formation)
  DEFAULT_RAM = ENV['VM_RAM'] || 2048
  DEFAULT_CPU = ENV['VM_CPU'] || 2
  config.ssh.forward_agent = false

  # 📂 Sync folder (utile pour scripts / Ansible)
#  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # =========================
  # 🧠 ANSIBLE
  # =========================
  config.vm.define "#{PREFIX}-ansible" do |ansible|
    ansible.vm.box = BOX
 #   ansible.vm.box_version = BOX_VERSION
    ansible.vm.hostname = "#{PREFIX}-ansible"
    ansible.vm.network "private_network", ip: "#{NETWORK}10"
    
    ansible.vm.provider "virtualbox" do |v|
      v.name = "#{PREFIX}-ansible"
      v.memory = DEFAULT_RAM
      v.cpus  = DEFAULT_CPU
    end
    ansible.vm.synced_folder "D:/TECH/Project/Smart-factory-iot-edge-to-cloud/11_TP_Deployment_Ansible", "/home/vagrant/projects", type: "virtualbox"

    ansible.vm.provision :shell do |shell|
      shell.path = "install_stack.sh"
      shell.args = ["ansible"]
    end
  end


  # =========================
  # 🏭 OPC UA PLC SIMULATOR
  # =========================
  config.vm.define "#{PREFIX}-opcua-plc-simulator" do |opc|
    opc.vm.box = BOX
 #   opc.vm.box_version = BOX_VERSION
    opc.vm.hostname = "#{PREFIX}-opcua-plc-simulator"
    opc.vm.network "private_network", ip: "#{NETWORK}11"
    

    opc.vm.provider "virtualbox" do |v|
      v.name = "#{PREFIX}-opcua-plc-simulator"
      v.memory = DEFAULT_RAM
      v.cpus  = DEFAULT_CPU
    end
    opc.vm.synced_folder "D:/TECH/Project/Smart-factory-iot-edge-to-cloud/02_TP_run_opcua_plc_simulator", "/home/vagrant/projects", type: "virtualbox"
    opc.vm.provision :shell do |shell|
      shell.path = "install_stack.sh"
      shell.args = ["opcua_plc_simulator"]
    end
  end


  # =========================
  # ⚙️ EDGE GATEWAY
  # =========================
  config.vm.define "#{PREFIX}-edge" do |edge|
    edge.vm.box = BOX
#    edge.vm.box_version = BOX_VERSION
    edge.vm.hostname = "#{PREFIX}-edge"
    edge.vm.network "private_network", ip: "#{NETWORK}12"
    

    edge.vm.provider "virtualbox" do |v|
      v.name = "#{PREFIX}-edge"
      v.memory = DEFAULT_RAM
      v.cpus  = DEFAULT_CPU
    end

    edge.vm.provision :shell do |shell|
      shell.path = "install_stack.sh"
      shell.args = ["edge"]
    end
  end

end