listener 1883
allow_anonymous true

connection aws-iot

address aee5b2mogflua-ats.iot.us-east-1.amazonaws.com:8883

topic factory/# out 1

bridge_cafile /mosquitto/certs/AmazonRootCA1.pem
bridge_certfile /mosquitto/certs/device.pem.cert
bridge_keyfile /mosquitto/certs/private.pem.key

bridge_insecure false
cleansession true
clientid edge-gateway

start_type automatic
try_private false
notifications false