apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb   
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true

    jsonData:
      version: Flux
      organization: iiot
      defaultBucket: edge-GW

    secureJsonData:
      token: $__file{/run/secrets/influx_token}