apiVersion: 1
policies:
    - orgId: 1
      receiver: SMTP_google
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: SMTP_google
          group_by:
            - grafana_folder
            - alertname
          object_matchers:
            - - severity
              - =
              - critical
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 1h
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
