apiVersion: 1

policies:
  - orgId: 1

    receiver: Email Contact   # default receiver

    group_by:
      - alertname

    routes:
      - receiver: Email Contact
        matchers:
          - severity = critical