---
- name: "deploy Edge-Gateway services"
  hosts: edge
  become: true
  vars_files:
  - vars.yml

  pre_tasks:
     - name: Install docker compose plugin
       ansible.builtin.apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes
  tasks:
     - name: Ensure directories exist
       file:
         path: "{{ item }}"
         state: directory
       loop:
         - /home/edge/edge-stack
         - /home/edge/data/node-red
         - /home/edge/edge-stack/secrets

     - name: Fix Node-RED permissions
       file:
          path: /home/edge/data/node-red
          owner: 1000
          group: 1000
          recurse: yes

     - name: Fix InfluxDB permissions
       file:
        path: /home/edge/data/influxdb
        owner: 1000
        group: 1000
        recurse: yes


     - name: Fix Grafana permissions
       file:
        path: /home/edge/data/grafana
        owner: 472
        group: 472
        recurse: yes


     - name: Copy edge gateway stack
       synchronize:
        src: ./files/
        dest: /home/edge/edge-stack/
        rsync_opts:
          - "--exclude=.env"
          - "--exclude=secrets"

     - name: Remove influx_token if it exists as directory
       file:
        path: /home/edge/edge-stack/secrets/influx_token.txt
        state: absent      
      
     - name: Copy secrets (controlled)
       copy:
          src: ./files/secrets/influx_token.txt
          dest: /home/edge/edge-stack/secrets/influx_token.txt
          owner: root
          group: root
          mode: '0444'

     - name: Deploy .env file (templated)
       template:
         src: .env.j2
         dest: /home/edge/edge-stack/.env
         mode: '0400'

     - name: Copy initial Node-RED flow if not exists
       copy:
        src: ./files/node-red/flows.json
        dest: /home/edge/data/node-red/flows.json
        owner: 1000
        group: 1000
        mode: '0644'
        force: no 

     - name: Run docker compose
       command: docker compose up -d --build
       args:
        chdir: /home/edge/edge-stack

  