---
- name: "deploy Edge-Gateway services"
  hosts: edge
  become: true
  vars_files:
  - vars.yml

  pre_tasks:
     - name: Install docker compose plugin
       ansible.builtin.apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

     - name: Install rsync
       ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: yes
  tasks:
     - name: Ensure directories exist
       file:
         path: "{{ item }}"
         state: directory
       loop:
         - /home/vagrant/edge-stack
         - /home/vagrant/data/node-red
         - /home/vagrant/edge-stack/secrets
         - /home/vagrant/data/influxdb
         - /home/vagrant/data/grafana

     - name: Fix Node-RED permissions
       file:
          path: /home/vagrant/data/node-red
          owner: 1000
          group: 1000
          recurse: yes

     - name: Fix InfluxDB permissions
       file:
        path: /home/vagrant/data/influxdb
        owner: 1000
        group: 1000
        recurse: yes


     - name: Fix Grafana permissions
       file:
        path: /home/vagrant/data/grafana
        owner: 472
        group: 472
        recurse: yes

     - name: Copy edge gateway stack
       ansible.posix.synchronize:
        src: ./files/
        dest: /home/vagrant/edge-stack/
        delete: yes
        rsync_opts:
          - "--exclude=.env"
          - "--exclude=secrets"
          - "--exclude=data"
          - "--exclude=node-red"
       
     - name: Remove influx_token if it exists as directory
       file:
        path: /home/vagrant/edge-stack/secrets/influx_token.txt
        state: absent      
      
     - name: Copy secrets (controlled)
       copy:
          src: ./files/secrets/influx_token.txt
          dest: /home/vagrant/edge-stack/secrets/influx_token.txt
          owner: root
          group: root
          mode: '0444'

     - name: Deploy .env file (templated)
       template:
         src: .env.j2
         dest: /home/vagrant/edge-stack/.env
         mode: '0400'

     - name: Run docker compose
       command: docker compose up --build -d
       args:
        chdir: /home/vagrant/edge-stack

  